//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunchViewer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LunchViewer.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Appearance.
        /// </summary>
        public static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @AutomaticUpdate.
        /// </summary>
        public static string AutomaticUpdate {
            get {
                return ResourceManager.GetString("AutomaticUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @BrowseForFile.
        /// </summary>
        public static string BrowseForFile {
            get {
                return ResourceManager.GetString("BrowseForFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @CheckForMenus.
        /// </summary>
        public static string CheckForMenus {
            get {
                return ResourceManager.GetString("CheckForMenus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @CheckForMenusNow.
        /// </summary>
        public static string CheckForMenusNow {
            get {
                return ResourceManager.GetString("CheckForMenusNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @CheckingMenusNotification.
        /// </summary>
        public static string CheckingMenusNotification {
            get {
                return ResourceManager.GetString("CheckingMenusNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @CheckNow.
        /// </summary>
        public static string CheckNow {
            get {
                return ResourceManager.GetString("CheckNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ClearAll.
        /// </summary>
        public static string ClearAll {
            get {
                return ResourceManager.GetString("ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ClearAllWarning.
        /// </summary>
        public static string ClearAllWarning {
            get {
                return ResourceManager.GetString("ClearAllWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @CollapseAll.
        /// </summary>
        public static string CollapseAll {
            get {
                return ResourceManager.GetString("CollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ColorTheme.
        /// </summary>
        public static string ColorTheme {
            get {
                return ResourceManager.GetString("ColorTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @DailyReminder.
        /// </summary>
        public static string DailyReminder {
            get {
                return ResourceManager.GetString("DailyReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Data.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @EnableDailyReminder.
        /// </summary>
        public static string EnableDailyReminder {
            get {
                return ResourceManager.GetString("EnableDailyReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ExpandAll.
        /// </summary>
        public static string ExpandAll {
            get {
                return ResourceManager.GetString("ExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @FontSize.
        /// </summary>
        public static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @FontSizeLarge.
        /// </summary>
        public static string FontSizeLarge {
            get {
                return ResourceManager.GetString("FontSizeLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @FontSizeSmall.
        /// </summary>
        public static string FontSizeSmall {
            get {
                return ResourceManager.GetString("FontSizeSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @MadeBy.
        /// </summary>
        public static string MadeBy {
            get {
                return ResourceManager.GetString("MadeBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Minutes.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @NewMenusNotification.
        /// </summary>
        public static string NewMenusNotification {
            get {
                return ResourceManager.GetString("NewMenusNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @NotificationDuration.
        /// </summary>
        public static string NotificationDuration {
            get {
                return ResourceManager.GetString("NotificationDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notifications.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @OpenTodaysMenu.
        /// </summary>
        public static string OpenTodaysMenu {
            get {
                return ResourceManager.GetString("OpenTodaysMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Overview.
        /// </summary>
        public static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Reminder.
        /// </summary>
        public static string Reminder {
            get {
                return ResourceManager.GetString("Reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @RepositoryPath.
        /// </summary>
        public static string RepositoryPath {
            get {
                return ResourceManager.GetString("RepositoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Seconds.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ShowNotifications.
        /// </summary>
        public static string ShowNotifications {
            get {
                return ResourceManager.GetString("ShowNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ShowTodaysMenu.
        /// </summary>
        public static string ShowTodaysMenu {
            get {
                return ResourceManager.GetString("ShowTodaysMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ThemeModernUIDark.
        /// </summary>
        public static string ThemeModernUIDark {
            get {
                return ResourceManager.GetString("ThemeModernUIDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ThemeModernUILight.
        /// </summary>
        public static string ThemeModernUILight {
            get {
                return ResourceManager.GetString("ThemeModernUILight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @TranslateMenus.
        /// </summary>
        public static string TranslateMenus {
            get {
                return ResourceManager.GetString("TranslateMenus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Updates.
        /// </summary>
        public static string Updates {
            get {
                return ResourceManager.GetString("Updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Week.
        /// </summary>
        public static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @WeeklyMenuHeader.
        /// </summary>
        public static string WeeklyMenuHeader {
            get {
                return ResourceManager.GetString("WeeklyMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @WeeklyMenuLink.
        /// </summary>
        public static string WeeklyMenuLink {
            get {
                return ResourceManager.GetString("WeeklyMenuLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
